url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "<span style='color: forestgreen;'>Yağmur Kiper <small><i>(she/her/o)</i></small></span>" # the name of your site, styled with forest green
description: "[jaːmuɾ kipɛɾ]"
