menu:
- {name: 'about me', url: '/'}
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'presentations', url: '/presentations'}
- {name: 'teaching', url: '/teaching'}
- {name: 'cv', url: '/_data/cv.pdf, external: true}

social:
  - {icon: 'fab fa-github', link: 'https://github.com/yagmurkiper'}
  - {icon: 'fas fa-graduation-cap', link: 'https://scholar.google.com/citations?user=_4wll80AAAAJ&hl=en&oi=ao'}
  - {icon: 'fab fa-linkedin', link: 'https://linkedin.com/in/yagmur-kiper'}
  - {icon: 'fab fa-orcid', link: 'https://orcid.org/0000-0003-1430-2424'}
